version: '3.8'

services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - 5432:5432
        volumes:
            - ./library_back/.env:/.env
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
    backend:
        build: 
            context: ./library_back
            dockerfile: Dockerfile
        container_name: backend
        environment:
            - DJANGO_SETTINGS_MODULE=src.settings
        volumes:
            - ./library_back:/var/www
        ports:
            - 8000:8000
        depends_on:
            postgres:
                condition: service_healthy
    frontend:
        build:
            context: ./library_front
            dockerfile: Dockerfile
        container_name: frontend
        volumes:
            - './library_front:/app'
        ports:
            - '3000:3000'
        depends_on:
            - backend