version: '3'
services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - 5432:5432
    library_app:
        build: .
        container_name: library_app_backend
        environment:
            - DJANGO_SETTINGS_MODULE=src.settings
        volumes:
            - .:/var/www
        ports:
            - 8000:8000
        depends_on:
            - postgres